wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.35.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697789702.857641
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 19
      - 23
      - 24
      4: 3.11.0
      5: 0.15.12
      6: 4.35.0.dev0
      8:
      - 3
      - 5
      13: windows-amd64
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.2
lstm_num_layers:
  desc: null
  value: 2
hidden_size:
  desc: null
  value: 128
bidirectional:
  desc: null
  value: true
optimizer:
  desc: null
  value: AdamW
loss_function:
  desc: null
  value: CrossEntropy
